# Generated by Django 5.0.3 on 2024-04-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buyers_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers_data',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
